name: Release

on:
  push:
    tags:
      - 'release-*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Extract version from tag
      id: version
      run: |
        TAG=${GITHUB_REF#refs/tags/release-}
        echo "VERSION=$TAG" >> $GITHUB_OUTPUT
        echo "Extracted version: $TAG"
    
    - name: Run tests
      run: ./gradlew test
    
    - name: Build JAR
      run: ./gradlew build
    
    - name: Publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ steps.version.outputs.VERSION }}
      run: ./gradlew publish
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/libs/*.jar
        tag_name: ${{ github.ref_name }}
        name: Release ${{ steps.version.outputs.VERSION }}
        body: |
          ## CompressGps Release ${{ steps.version.outputs.VERSION }}
          
          ### Features
          - High-performance GPS telemetry compression for racing applications
          - Adaptive sampling with zone classification
          - Lap-based chunking for corruption resilience
          - Binary compression with 93%+ space savings
          
          ### Usage
          ```kotlin
          dependencies {
              implementation("com.normtronix:CompressGps:${{ steps.version.outputs.VERSION }}")
          }
          ```
          
          ### Files
          - `CompressGps-${{ steps.version.outputs.VERSION }}.jar` - Main library JAR
          - `CompressGps-${{ steps.version.outputs.VERSION }}-sources.jar` - Source code JAR
        generate_release_notes: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}